spring:
  application:
    name: diversao-backend
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate # será sobrescrito em dev, mas mantemos como default seguro
  flyway:
    enabled: false # em dev desabilitamos; em prod habilitamos via perfil
  jackson:
    default-property-inclusion: non_null

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always

jwt:
  secret: ${JWT_SECRET:}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:2592000000}   # 30d

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG